services:
  - type: web
    name: price-tracker-backend
    dockerfilePath: Dockerfile
    plan: free
    python:
      version: "3.11.8"  
    envVars:
      - key: PIP_NO_CACHE_DIR
        value: "1"